# Generated by Django 4.0.3 on 2022-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IttifoqSardorlarLoyihasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Itifoq')),
                ('project_name', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='KamalakSardorlarLoyihasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='kamalak')),
                ('project_name', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Platformaga_qiziqishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiziqish', models.CharField(choices=[('yaxshi', 'yaxshi'), ("zo'r", "zo'r")], default='Yaxshi', max_length=9)),
                ('coment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sardorlarhaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='kamalak')),
                ('full_name', models.CharField(max_length=2500)),
                ('yunalishi', models.CharField(max_length=2550)),
            ],
        ),
    ]
