# Generated by Django 4.0.3 on 2022-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelajak_yoshlariapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murojaat', models.CharField(max_length=50000)),
                ('telefon_raqam', models.CharField(max_length=50000)),
            ],
        ),
    ]
