# Generated by Django 4.0.3 on 2022-04-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kelajak_yoshlariapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savolni_soni', models.CharField(max_length=500)),
                ('savol', models.CharField(max_length=5000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savollarga_javob_yozish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savolga_javobni_yozish', models.CharField(max_length=5000)),
                ('telfon_raqam', models.CharField(max_length=20)),
                ('savolni_sonini_belgilash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelajak_yoshlariapp.savollar')),
            ],
        ),
    ]
